#!/bin/sh

E='HDMI-2'
I='LVDS-1'
DN='0x0 0xA 0xB 0xC 0xD 0xE'

if [ $(bspc query -M | wc -l) -eq 2 ]; then
	xrandr --output $I --off --output $E --auto
	bspc monitor $E -d $DN
	bspc desktop Desktop --remove > /dev/null
	bspc monitor $I -r
	walp
else
	bspc monitor -d $DN
fi

xsetroot -cursor_name left_ptr

bspc config border_width         7
bspc config window_gap           7
bspc config top_padding          19

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focus_follows_pointer true
bspc config pointer_follows_focus true
bspc config pointer_follows_monitor true

bspc config normal_border_color "#5c6370"
bspc config focused_border_color "#61afef"
bspc config presel_feedback_color "#5c6370"

bspc rule -a "firefox" desktop='^2'
bspc rule -a "TelegramDesktop" desktop='^5' state=floating
bspc rule -a "feh" state=pseudo_tiled

pgrep -x panel > /dev/null || panel &
dborders &
