#!/bin/sh
#
# script for exporting battery to lemonbar.

BAT_DIR='/sys/class/power_supply/BAT0'

while true; do
	read -r sts < $BAT_DIR/status

	case "$sts" in
		"Discharging")
			read -r cap < $BAT_DIR/capacity

			cap=$((cap / 25))

			case "$cap" in
				4|3) var="" ;;
				# '4'|'3') var="%{F#5c6370}%{F-}" ;;
				2)   var="" ;;
				# '2') var="%{F#98c379%{F-}" ;;
				1)   var="" ;;
				# '1') var="%{F#e5c07b%{F-}" ;;
				0)   var="" ;;
				# '0') var="%{F#e06c75}%{F-}" ;;
				*) var=''
			esac ;;
		"Charging")
			var="" ;;
		*)
			var='%{R}%{R-}' ;;
	esac

	printf "%s\n" "bat $var"

	sleep 10
done
