#!/bin/sh
#
# script for exporting battery to lemonbar.

BAT_DIR='/sys/class/power_supply/BAT0'

while true; do
	read -r sts < $BAT_DIR/status
	read -r cap < $BAT_DIR/capacity

	if [ "$sts" == "Discharging" ]; then
		[ "$cap" -le 15 ] && var=" $cap" || # Warning
			var=" $cap" # Heart
	else
		[ "$sts" == "Charging" ] && var=" $cap" || # Charging
			var='' # Fully charged
	fi

	printf "%s\n" "bat $var"

	sleep 10
done
