#!/bin/sh
#
# script for exporting current song and artist playing in mpd to lemonbar.
#
# dependencies: mpc
#
# credits: https://github.com/turquoise-hexagon/dots

while true
do
	mpc | {
		read -r inf
		read -r sts

		case "$sts" in
			*playing*) var=" $inf";;
			*paused*)  var=" $inf";;
			*) var='';;
		esac

		printf "%s\n" "mus $var"
	}
	
	mpc idle player
done
