#!/bin/sh
#
# export current track and artist to lemonbar using playerctl
#
# dependencies: playerctl

while true; do
	$(ps -C spotify > /dev/null) &&
		var=" $(playerctl metadata --format '{{artist}} · {{title}}')" ||
		var=''

	printf "%s\n" "mus $var"

	sleep 3
done
