#!/bin/sh
#
# script for exporting ssid and ip to lemonbar.
# dependencies: iwd

device="wlan0"

while true; do
	ipa=$(for i in `ip r`; do echo $i; done | grep -A 1 src | tail -1)
	# ssid=$(nmcli device | awk '{if ($2 == "wifi") {print $4}}')
	ssid=$(iwctl station $device show | awk '{if ($1 == "Connected") {print $NF}}')

	if [ -z "$ssid" ]; then # if no ssid we're either wired or disconnected
		[ -z "$ipa" ] && net='%{F#61afef}Ø%{F-}' || net="$ipa"
	else # else we have a wireless connection
		net="%{F#61afef}λ%{F-} $ssid"
	fi

	printf "%s\n" "ntw $net"

	sleep 1
done
