#!/bin/sh
#
# script for exporting volume to lemonbar.
#
# dependencies: pulseaudio|pipewire-pulse

while true
do
    sts=$(pactl get-sink-mute @DEFAULT_SINK@ | cut -d ' ' -f 2)

    case $sts in
        'no') von="%{F#c678dd}<%{F-} $(pactl get-sink-volume @DEFAULT_SINK@ \
            | awk '{print $5}' | cut -d '%' -f 1)" ;;
        'yes') von="%{F#e5c07b}!%{F-}" ;;
    esac

    printf "%s\n" "vol $von"

    sleep 1
done
