#!/bin/sh
#
# script for exporting volume to lemonbar.
#
# dependencies: alsa-utils

while true
do
    sts=$(amixer get Master | tail -1 | awk '{print $NF}')

    case $sts in
        '[on]') von="%{F#c678dd}§%{F-} $(amixer get Master \
            | tail -1 \
            | sed 's/.*\[\([0-9]*%\)\].*/\1/' \
            | cut -d "%" -f 1)" ;;
        '[off]') von="%{F#e5c07b}!%{F-}" ;;
    esac

    printf "%s\n" "vol $von"

    sleep 1
done
