#!/bin/sh
#
# ensure workspaces block isn't empty on startup
#
# dependencies: xtitle
# 
# credit: https://github.com/turquoise-hexagon/dots

{ echo; xtitle -s; } |
    while read -r win; do
        cur=$(bspc query -D -d --names)
        printf '%s\n' "wks @ %{F#c678dd}$cur%{F-}"
    done
